return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "pyright",
      "black",
      "bash-language-server",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "hadolint",
      "json-lsp",
      "lua-language-server",
      "markdown-toc",
      "markdownlint-cli2",
      "marksman",
      "prettier",
      "shfmt",
      "stylua",
      "taplo",
      "texlab",
      "yaml-language-server",
      "alex",
      "beautysh",
      "cspell",
      "isort",
      "shellcheck",
      "yamlfmt",
    },
  },
}
